"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, Optional
from fontTools.designspaceLib import DesignSpaceDocument, SimpleLocationDict

"""Compute name information for a given location in user-space coordinates
using STAT data. This can be used to fill-in automatically the names of an
instance:

.. code:: python

    instance = doc.instances[0]
    names = getStatNames(doc, instance.getFullUserLocation(doc))
    print(names.styleNames)
"""
LOGGER = ...
RibbiStyle = str
BOLD_ITALIC_TO_RIBBI_STYLE = ...
@dataclass
class StatNames:
    """Name data generated from the STAT table information."""
    familyNames: Dict[str, str]
    styleNames: Dict[str, str]
    postScriptFontName: Optional[str]
    styleMapFamilyNames: Dict[str, str]
    styleMapStyleName: Optional[RibbiStyle]
    ...


def getStatNames(doc: DesignSpaceDocument, userLocation: SimpleLocationDict) -> StatNames:
    """Compute the family, style, PostScript names of the given ``userLocation``
    using the document's STAT information.

    Also computes localizations.

    If not enough STAT data is available for a given name, either its dict of
    localized names will be empty (family and style names), or the name will be
    None (PostScript name).

    .. versionadded:: 5.0
    """
    ...

